# Generated by Django 5.1.4 on 2024-12-12 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hpk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When the article was last mutilated."
            ),
        ),
    ]
