# Generated by Django 5.1.4 on 2024-12-12 05:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hpk", "0002_alter_article_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=wagtail.fields.StreamField(
                [("section", 5), ("image", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for this section.", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Heading level",
                            "max_value": 6,
                            "min_value": 1,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ul", "ol", "document-link"]},
                    ),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 2), ("image", 3)]],
                        {"help_text": "Content blocks for this section.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("level", 1), ("content", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
