# Generated by Django 5.1.4 on 2025-01-01 05:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpk', '0007_splitviewpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitviewpage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('image', 4), ('social_links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': None, 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('plaintext', 'Plain Text')], 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('code', 1), ('language', 2)]], {}), 4: ('hpk.blocks.WrappedImageChooserBlock', (), {}), 5: ('hpk.blocks.StaticIconLinkListBlock', (), {})}, help_text='Main content for the split-view page.'),
        ),
    ]
